---
- hosts: all
  become: true
  tasks:
    
  - name: install the latest python3 and pip3
    apt:
      name: python3-pip
      state: latest
    vars:
      ansible_pip_interpreter: /usr/bin/pip3
      ansible_python_interpreter: /usr/bin/python3

  - name: install Java open-jdk
    apt:
      name: openjdk-17-jre
      state: latest

  - name: install MariaDB
    apt:
      name: mariadb-server
      state: latest
      update_cache: yes

  - name: start and enable mariadb server
    service:
      name: mariadb
      enabled: true
      state: started
